{
 "title": "Vista general",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Peticiones totales",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Peticiones totales por estado",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=\"200\"})",
     "legendFormat": "200"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=\"401\"})",
     "legendFormat": "401"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=\"403\"})",
     "legendFormat": "403"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=\"404\"})",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "Peticiones por minuto",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Peticiones por minuto"
    }
   ]
  },
  {
   "title": "Duración media peticiones (segundos)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum) / sum(http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Duración media peticiones en el tiempo (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "Duración media peticiones en el tiempo (segundos)"
    }
   ]
  },
  {
   "title": "Peticiones por ruta",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/friends/near\"})",
     "legendFormat": "Amigos cercanos"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/add\"})",
     "legendFormat": "Envío de localización"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/friends\"})",
     "legendFormat": "Todos los amigos"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/login\"})",
     "legendFormat": "Inicio de sesión"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/ban\"})",
     "legendFormat": "Banear/desbanear usuario"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"GET\",path=\"/api/user/banned\"})",
     "legendFormat": "Consultar usuario baneado"
    }
   ]
  },
  {
   "title": "Peticiones por ruta y minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/friends/near\"}[1m]))",
     "legendFormat": "Amigos cercanos"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/add\"}[1m]))",
     "legendFormat": "Envío de localización"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/friends\"}[1m]))",
     "legendFormat": "Todos los amigos"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/login\"}[1m]))",
     "legendFormat": "Inicio de sesión"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=\"POST\",path=\"/api/user/ban\"}[1m]))",
     "legendFormat": "Banear/desbanear usuario"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=\"GET\",path=\"/api/user/banned\"}[1m]))",
     "legendFormat": "Consultar usuario baneado"
    }
   ]
  }
 ]
}