[[section-introduction-and-goals]]
== Introducción y objetivos

[role="arc42help"]

Vamos a desarrollar Radarin, un sistema para facilitar encuentros entre amigos. Mediante una aplicación móvil podrá conocer cuando otro usuario amigo suyo esté cerca.

Radarin sigue las características SOLID, por lo que se servirá de PODS para garantizar la descentralización y la privacidad de nuestros usuarios.


=== Vista de requisitos

[role="arc42help"]

Radarin contempla unos requisitos mínimos de funcionamiento que pretenden ser la base desde la cual se pueda ofrecer al cliente la funcionalidad descrita, además de servir para futuras ampliaciones.

* Requisitos funcionales:

**  Un usuario podrá añadir a otros usuarios a su lista de amigos.

** Un usuario será capaz de ver otros usuarios agregados a su lista cercanos.

**  El sistema ofrecerá al usuario notificaciones si tiene amigos cerca.

**  Cada usuario podrá modificar sus localizaciones.

** El administrador del servicio tendrá opción de modificar usuarios y revisar el estado del servidor.

* Requisitos no funcionales:
**  Soporte completo con el proyecto SOLID.

**  La aplicación estará alojada en un servidor web que únicamente almacenará localizaciones del usuario, solicitando al mismo para acceder a la suya. 

**  Toda información que no sea una localización será almacenada en el pod de SOLID del usuario.

**  El servicio debe ser soportado por los dispositivos móviles de los usuarios, tomando los datos de geolocalización provenientes del mismo.

**  El sistema se desplegará desde contenedores docker y utlizará el servicio en la nube heroku.

=== Objetivos de calidad

[role="arc42help"]

Los objetivos de calidad ordenados de mayor a menor prioridad, son los siguientes: 

[options="header",cols=2*]
|===
|Objetivo|Descripción
| 1.Software mantenible y extensible | Debemos poder mantener y extender nuestro software facilmente en todo momento. 
| 2.Privacidad | Se almacenará la información mínima necesaria para cada ususario de la aplicación. En el caso de que se necesite información adicional de un ususario en concreto, se le pedirá permiso para obtener dicha información a través de su pod. 
| 3.Usabilidad | La aplicación debe de ser fácil de usar e intuitiva para todo tipo de ususarios.
| 4.Testeable | Nuestra aplicación debe poder probarse tanto manual como automaticamente. Esto nos permitirá comprobar facilmente el correcto funcionamiento del sistema.
| 5.Rendimiento | La aplicación debe mantener una capacidad de respuesta lo más rápida posible en todo momento.
|===


=== Stakeholders

[role="arc42help"]

.Contenido
Descripción general explícita de las partes interesadas del sistema, es decir, todas las personas, roles u organizaciones que

* deben conocer la arquitectura
* tienen que estar convencidos de la arquitectura
* tienen que trabajar con la arquitectura o con el código
* necesitan la documentación de la arquitectura para su trabajo
* tienen que tomar decisiones sobre el sistema o su desarrollo

.Motivación
Se debe conocer a todas las partes involucradas en el desarrollo del sistema o afectadas por el sistema.
De lo contrario, puede recibir sorpresas desagradables más adelante en el proceso de desarrollo.
Estos interesados determinan el alcance y el nivel de detalle de su trabajo y sus resultados.

.Forma
Tabla con nombres de roles, nombres de personas y sus expectativas con respecto a la arquitectura y su documentación.


[options="header",cols="1,2,2"]
|===
|Rol/Nombre|Contacto|Expectativas
| _<Usuarios>_ | _<Usuarios potenciales>_ | _<Usuarios finales interesados en utilizar la aplicación>_
| _<Equipo de desarrollo>_ | _<Equipo que crea la aplicación>_ | _<Creación de una aplicación estable, segura y estética>_
| _<Profesores>_ | _<Profesores de la asignatura ASW>_ | _<Supervisan el proyecto y se aseguran de que se cumplan los requisitos.>_
|===
