[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Vista de requisitos

[role="arc42help"]
****
* Funcionales
  ** Los usuarios deben de poder ver las rutas en un mapa
  ** Los usuarios deben de poder guardar rutas
  ** Un usuario debe poder compartir rutas con otros usuarios los cuales seran notificados si reciben una ruta
  ** Los datos de un usuario seran guardados de manera descentralizada
  ** Los usuarios podran crear grupos entre ellos y podran compartir diferentes tipos de archivos entre si
* No Funcionales
  ** Se mantendrán descentralizados los datos para mantener mas segura la informacion del usuario
  ** El sistema debe de poder comunicarse con otros sistemas de gestion de rutas
  ** El sistema sera utilizable por cualquier tipo de usuario
  ** El sitema debe de poder tratar con multiples usuarios al mismo tiempo
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contenido
Descripción general explícita de las partes interesadas del sistema, es decir, todas las personas, roles u organizaciones que

* deben conocer la arquitectura
* tienen que estar convencidos de la arquitectura
* tienen que trabajar con la arquitectura o con el código
* necesitan la documentación de la arquitectura para su trabajo
* tienen que tomar decisiones sobre el sistema o su desarrollo

.Motivación
Se debe conocer a todas las partes involucradas en el desarrollo del sistema o afectadas por el sistema.
De lo contrario, puede recibir sorpresas desagradables más adelante en el proceso de desarrollo.
Estos interesados determinan el alcance y el nivel de detalle de su trabajo y sus resultados.

.Forma
Tabla con nombres de roles, nombres de personas y sus expectativas con respecto a la arquitectura y su documentación.
****

[options="header",cols="1,2,2"]
|===
|Rol/Nombre|Contacto|Expectativas
| _<Usuarios>_ | _<Usuarios potenciales>_ | _<Usuarios finales interesados en utilizar la aplicación>_
| _<Equipo de desarrollo>_ | _<Equipo que crea la aplicación>_ | _<Creación de una aplicación estable, segura y estética>_
| _<Profesores>_ | _<Profesores de la asignatura ASW>_ | _<Supervisan el proyecto y se aseguran de que se cumplan los requisitos.>_
|===
