[[section-introduction-and-goals]]
== Introducción y objetivos

Vamos a desarrollar Radarin, un sistema para facilitar encuentros entre amigos. Estará compuesta de: 

* Aplicacion movil: enviará una notificación a los usuarios cuando un amigo suyo este cerca y también permitirá compartir su ubicación.

* Aplicación web: permitirá a los usuarios visualizar y gestionar sus localizaciones. También incluirá opciones de administración de usuarios y monitorización del estado del servidor. Esta aplicación estará alojada en un servidor que almacenará las locaclizaciones de los usuarios. 


=== Vista de requisitos

* Requisitos funcionales:

**  Un usuario podrá añadir a otros usuarios a su lista de amigos. 

**  Un usuario será capaz de ver la localización de sus amigos cercanos.

**  La aplicación movil notificará al usuario si tiene amigos cerca.

**  Cada usuario podrá gestionar sus localizaciones.

** El administrador del sistema tendrá opción de gestionar usuarios y revisar el estado del servidor.

* Requisitos no funcionales:
**  El sistema debde de ser compatible con el proyecto SOLID.

**  La aplicación web estará alojada en un servidor que únicamente almacenará localizaciones del usuario. 

**  Toda información que no sea una localización será almacenada en el pod de SOLID del usuario.

**  Se toman los datos de geolocalización provenientes del dispositivo movil de los usuarios.

**  El sistema se desplegará desde contenedores docker en un servicio en la nube.

=== Objetivos de calidad

Los objetivos de calidad ordenados de mayor a menor prioridad, son los siguientes: 

[options="header",cols=2*]
|===
|Objetivo|Descripción
| 1.Privacidad | Se almacenará la información mínima necesaria para cada usuario de la aplicación.
| 2.Usabilidad | La aplicación debe de ser fácil de usar e intuitiva para todo tipo de usuarios. 
| 3.Mantenibilidad | Debemos poder mantener y extender nuestro software facilmente en todo momento. 
| 4.Testeabilidad | Esto nos permitirá comprobar facilmente el correcto funcionamiento del sistema.
| 5.Rendimiento | La aplicación debe mantener una capacidad de respuesta lo más rápida posible en todo momento.
|===


=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Rol/Nombre|Contacto|Expectativas
| Usuarios | Usuarios potenciales | Usuarios finales interesados en utilizar la aplicación.
| Equipo de desarrollo | Equipo que crea la aplicación (ES4-B) | Creación de una aplicación estable, segura y estética.
| Clientes | Profesores de la asignatura ASW | Supervisan el proyecto y se aseguran de que se cumplan los requisitos.
|===
