[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Vista de requisitos

[role="arc42help"]
****
* Funcionales
  ** Los usuarios deben de poder ver las rutas en un mapa
  ** Los usuarios deben de poder guardar rutas
  ** Un usuario debe poder compartir rutas con otros usuarios los cuales seran notificados si reciben una ruta
  ** Los datos de un usuario seran guardados de manera descentralizada
  ** Los usuarios podran crear grupos entre ellos y podran compartir diferentes tipos de archivos entre si
* No Funcionales
  ** Se mantendrán descentralizados los datos para mantener mas segura la informacion del usuario
  ** El sistema debe de poder comunicarse con otros sistemas de gestion de rutas
  ** El sistema sera utilizable por cualquier tipo de usuario
  ** El sitema debe de poder tratar con multiples usuarios al mismo tiempo
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
