[[section-system-scope-and-context]]
== Alcance y contexto del sistema

El objetivo principal de este proyecto es crear un sistema para facilitar encuentros entre amigos.  
Este sistema estará descentralizado y basado en SOLID, lo que significa que cada usuario tendrá su propio pod. 
El pod es el  espacio de almacenamiento propio donde cada ususario almacenará toda su información. 
Los principales socios de comunicación del sistema serán los propios usuarios. Radarin será el intermediario entre Solid y el usuario.

=== Contexto empresarial

|=========================================================
| Socio de comunicación |Entradas |Salidas

| Usuario
| Su ubicación geográfica y la URL de su pod. 
| Las ubicaciones de los amigos

| Pod
| 
| Información propia del usuario


[plantuml,"Diagrama contexto empresarial",png]
----
@startuml
actor Usuario
package "Radarin" {
}
package "Pod" {
}
Usuario -left-> Radarin: Ubicación y URL de su Pod
Radarin -right-> Usuario: Ubicaciones de los amigos
Pod -> Radarin: Información del usuario
@enduml
----

|=========================================================

=== Contexto técnico

Interfaces técnicas:

[options="header",cols="1,2"]
|===
| Objeto | Descripción 

| Aplicación web y movil
| Canal de comunicación entre los ususarios y el sistema. 

| Https
| Comunicación a través del protocolo Https entre el usuario y la aplicación web.También permite la comunicación entre el pod y el sistema. 
|===

[plantuml,"Diagrama contexto tecnico",png]
----
@startuml
node Pod
actor Usuario
package "Radarin" {
    node Aplicación_movil
    package Servidor_web {
        node Aplicación_web
    }
}
Usuario -right- Aplicación_movil
Servidor_web -down- Pod: HTTPS
Usuario -up- Aplicación_web: HTTPS
@enduml
----