[[section-system-scope-and-context]]
== Alcance y contexto del sistema

El objetivo principal de este proyecto es crear un sistema para facilitar encuentros entre amigos.  
Este sistema estará descentralizado y basado en SOLID, lo que significa que cada usuario tendrá su propio pod. 
El pod es el  espacio de almacenamiento propio donde cada ususario almacenará toda su información. 
Los principales socios de comunicación del sistema serán los propios usuarios. Radarin será el intermediario entre Solid y el usuario.

[plantuml,"Sequence diagram",png]
----
	left to right direction
	skinparam packageStyle rect
	actor userA
	actor userB
	rectangle Solid {
	  userA -- (Radarin)
	  (Radarin) -- userB
	}
----

=== Contexto empresarial

|=========================================================
| Socio de comunicación |Entradas |Salidas

| Usuario
| Su ubicación geográfica y la URL de su pod. 
| Las ubicaciones de los amigos

| Pod
| 
| Información propia del usuario

|=========================================================

=== Contexto técnico

Interfaces técnicas:

[options="header",cols="1,2"]
|===
| Objeto | Descripción 

| Aplicación web y movil
| Canal de comunicación entre los ususarios y el sistema. 

| Https
| Comunicación a través del protocolo Https entre el usuario y la aplicación web.También permite la comunicación entre el pod y el sistema. 
|===
