[[section-system-scope-and-context]]
== Alcance y contexto del sistema


[role="arc42help"]

.Contents
El objetivo principal de este proyecto es crear un sistema para facilitar encuentros entre amigos, 
este sistema estará descentralizado y basado en SOLID, lo que significa que cada usuario tendrá su propio Pod, 
que es su propio espacio de almacenamiento personal, donde se almacenará toda su información. 
Los principales socios de comunicación de las aplicaciones serán los propios usuarios, radarin será el intermediario entre Solid y el usuario.
<<<<<<< HEAD

@startuml
	left to right direction
	skinparam packageStyle rect
	actor userA
	actor userB
	rectangle checkout {
	  user -- (Radarin)
	  (Radarin) -- userB
	}
@enduml
=======

=== Contexto empresarial

[role="arc42help"]
****
.Contents
.Radarin
|=========================================================
| Socio de comunicación |Entradas |Salidas

| Usuario
| Registrar ubicación. Ver las ubicaciones de los amigos

| POD
| Can store routes in a interoperable route format
| Allow viade to read the routes stored inside

| Radarin
| Routes and multimedia 
| Routes and push notifications

| Otros usuarios
| 
| Receives push notifications when a route is shared

|=========================================================

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****

**<Diagram or Table>**

**<optionally: Explanation of external domain interfaces>**

=== Contexto técnico

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
