[[section-building-block-view]]


== Vista de bloques de creación

=== Diagrama general del sistema
Esta es una descomposición de la aplicación en diferentes niveles, desde lo más general a lo más específico:

[plantuml,"Nivel 1",png]
----
@startuml
actor Usuario
package Radarin {
    node Aplicación_movil
    node Servidor_web #grey;text:white
}
agent "Pod"
database BD
Usuario <-right-> Servidor_web: HTTPS
Usuario <-right-> Aplicación_movil
Aplicación_movil <-right->  Servidor_web: HTTPS
Pod <-down-> Servidor_web: HTTPS / RDF
BD<-left-> Servidor_web: MongoDB Wire
@enduml
----

El sistema (Radarin) se descompone en una aplicación movil y un servidor web. El usuario se comunica con la aplicación movil y el servidor web. El servidor se comunica con los pods. La aplicación movil se comunicará con parte del servidor web. 

[options="header",cols="1,2"]
|===
|Caja negra|Descripción
| Servidor web | almacena las ubicaciones de los usuarios, aloja una aplicación web y se comunica con los pods. 
|===

=== Nivel 2 

==== Servidor web

[plantuml,"Nivel 2",png]
----
@startuml
actor Usuario
node Aplicación_movil
package Servidor_web {
   node Aplicación_web
   node API_REST
}
database BD
agent "Pod"
Usuario <-right-> Aplicación_web: HTTPS
Usuario <-right-> Aplicación_movil
Aplicación_movil <-right->  API_REST: HTTPS / REST
Pod <-down-> API_REST: HTTPS / RDF
Aplicación_web <-down-> API_REST: HTTPS / REST
Aplicación_web <-right-> Pod: HTTPS / RDF
API_REST <-down-> BD: MongoDB Wire
@enduml
----

El servidor web aloja una aplicación web, una API Rest y una base de datos. La aplicación web y la aplicación movil realizan peticiones a la API Rest. La API Rest consulta a la base de datos y a los pods y envía las respuestas a las aplicaciones. 
