[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Enviar Posicion>


* Permitir a la aplicacion saber tu posicion

[plantuml,"Sequence diagram",png]
----
actor Alice
participant  Radarin
particiopant Pod
entity Location
Alice -> Radarin: Da permiso usar la localizacion
Radarin -> Pod: Busca la localizacion
Pod -> Alice: Pide la localizacion
Alice -> Location: Genera la localizacion
Location -> Pod: La localizacion se envia al pod
Pod -> Radarin: El pod envia la localizacion a la app
Radarin -> Alice: Aviso de envio correcto
----
=== <Dar localizacion a un amigo>
* Permitir a la aplicacion saber tu posicion y enviarla a otro usuario

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
participant  Radarin
particiopant Pod
entity Location
Alice -> Radarin: Da permiso usar la localizacion
Radarin -> Pod: Busca la localizacion
Pod -> Alice: Pide la localizacion
Alice -> Location: Genera la localizacion
Location -> Pod: La localizacion se envia al pod
Pod -> Radarin: El pod envia la localizacion a la app
Radarin-> Bob: La aplicacion le envia la posicion de Alice a Bob
Radarin -> Alice: Aviso de envio correcto
----
