[[section-concepts]]
== Conceptos transversales

A continuación se describen los principales elementos, regulaciones y soluciones que son relevantes en Radarin.

.Modelo de dominio
* Usuario: Individuo físico que posee y utiliza la aplicación móvil en su dispositivo.
* POD: Sistema para almacenar la información del usuario. Es el usuario el que tiene el control sobre su información.
* Servidor web: alojará la aplicación web, la API REST y la base de datos.
* Amigos: Son todos los usuarios que permiten a otro usuario acceder a su información.

.Conceptros de desarrollo
A través de GitHub, usaremos Codacy para verificar la calidad del código, y Codecov para comprobar la cobertura de las pruebas.
En cuanto a las pruebas, usaremos Jest en el caso de la API Rest y el script de test de react-scripts en el caso de la aplicación web.

.Seguridad e información
La información de nuestros usuarios está descentralizada gracias a los PODs. De esta manera garantizamos su independencia y seguridad.
Para autenticar los accesos a la API Rest desde la aplicación móvil usaremos un token que será enviado al usuario cuando inicie sesión y se almacenará encriptado en su dispositivo. Cada vez que se haga una petición a la API que requiera autenticación, tendrá que enviarse el token para su verificación. 
Los usuarios administradores acceden al sistema mediante un Pod específico.

.Monitorización
Usaremos un servidor Prometheus para almacenar los datos de monitorización de la API REST desplegada. Para visualizar los datos almacenados por Prometheus usaremos un servidor Grafana. Ambos servidores se desplegarán como contenedores Docker en local y accederán a los datos de la API en la nube.
