[[section-design-decisions]]
== Decisiones de diseño


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****

=== ADR 1: Usar JavaScript con Node.js como lenguaje de programación
==== Contexto
Tenemos que elegir un lenguaje de programación para desarrollar la aplicación web y la API REST. Debe ser un lenguaje que
permita computación del lado del servidor.

==== Decisión
Hemos decidido usar JavaScript con Node.js para desarrollar la aplicación web y la API. Hemos tomado esta decisión porque es uno
de los lenguajes más populares en la actualidad y tenemos un poco de experiencia trabajando con JavaScript del lado del cliente.
Además también vamos a usar este lenguaje en la asignatura SDI, por lo que podemos aprovechar los conocimientos obtenidos en ambas asignaturas.

==== Estado
Aprobada.

==== Consecuencias
Usaremos JavaScript con Node.js como lenguaje de programación. Tendremos que aprender a usar Node.js y podremos usar uno de los muchos
frameworks JavaScript que existen actualmente.

=== ADR 2: Usar React como framework para la interfaz gráfica
==== Contexto
Debemos elegir un framework JavaScript para diseñar la interfaz gráfica tanto de la aplicación web como de la aplicación móvil. 
No tenemos conocimiento previo sobre ningún framework, así que la experiencia no influirá en la decisión. Algunos de los frameworks JavaScript
más populares en la actualidad son React, Angular y Vue.

==== Decisión
Hemos decidido usar React como framework para la interfaz gráfica porque es uno de los más populares actualmente y es el
que nos proponen desde la asignatura. Además, permite diseñar tanto aplicaciones web como aplicaciones móviles y existen librerías con componenetes para
trabajar con Solid.

==== Estado
Aprobada.

==== Consecuencias
Usaremos React para diseñar la aplicación web y la aplicación móvil. No tenemos experiencia previa con React, así que
tendremos que documentarnos y aprender a usar este framework.


