[[section-technical-risks]]
== Riesgos y deuda técnica


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

* Falta de experiencia con el framework React. Deberíamos documentarnos correctamente antes de empezar a usarlo.
* Escasa madurez de Solid, será más difícil encontrar soluciones a los problemas que se nos planteen.
* Poca experiencia trabajando con JavaScript, y ninguna trabajando con Node.js. También deberíamos documentarnos antes de empezar.
